### ISSUE TITLE
1 Missing entity in BLOCK reference in dwg2dxf

### ISSUE THREAD

**Issue by soundd1** [LibreDWG/libredwg#143]
Hi,
When I convert dwg to dxf, I noticed that there are some problems below :
-1 missing entity in Block reference.
- Entity color is converted ByBlock instead of ByLayer or RGB,
- BLOCKINSERT is missing,
- Some error messages in some dwg files.

Simple test file is attached,
Thanks 
[testBlock.zip](https://github.com/LibreDWG/libredwg/files/3608547/testBlock.zip)

**Comment by rurban** [comment]
Yes, there's something with the default color, HEADER.CECOLOR already, leading to all sorts of subsequent HEADER errors. Investigating.
The NOD is also wrong (Named Objects Dictionary), and other dicts also.
And the objects after LINE 0.2.7542 are all corrupt. Very interesting, thanks a lot!

**Comment by rurban** [comment]
Found and fixed the problem. There are overlarge handles needing >4 byte, up to 8 byte.
E.g. D485E5D6
You deleted a lot of objects there. I bumped the size limit from 4 to 8.

**Comment by rurban** [comment]
wrong ByBlock color fixed with 87ef5e7d

**Comment by rurban** [comment]
wrong DXF INSERT.block_header 2 (name) fixed with 92f6dbf2d16fd2ebdb9ef395fad073029fe454dc

**Comment by soundd1** [comment]
Hi rurban, thanks for fixing most of problems. But 1 thing is continuing. 1 entity is still missing in BLOCK. I attached an image :
![missingentity](https://user-images.githubusercontent.com/44694004/65499091-c1a12d80-dec5-11e9-9c4b-dc87ce507024.png)

**Comment by soundd1** [comment]
Oh ok, thanks 👍

**Comment by rurban** [comment]
More todos:
* CLASS desc  3 "TCH_KERNAL|缺乏解释器天正图形看不见, 请下载天正插件|网址: www.tangent.com.cn"
is converted to "TCH_KERNAL|:O��h)c�b
�, �})c��|Q@: www.tangent.com.cn"
...

**Comment by rurban** [comment]
Fixed the unicode problem with 63c70e57ef59aef8612d413507adf026f1e59a58
Now the sampleBlock still misses the CIRCLE and has a wrong base_pt.

**Comment by rurban** [comment]
should be fixed now. in master and 0.9 soon. 3051810b6ebb5d7327755cad70fd1fd1e614abbb
